"use client";

import Link from "next/link";
import { ArrowRight, Check, Clapperboard, FileText, Languages, LockKeyhole, Megaphone, Play, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Pattern = { id: string; title: string; status: string; behavioural_pattern?: string; complaint_count: number; indicators: { type_label: string; display_value: string; case_count: number }[] };

export function AwarenessStudio() {
  const [patterns, setPatterns] = useState<Pattern[]>([]);
  const [selectedId, setSelectedId] = useState("");
  const [format, setFormat] = useState("60-second video script");
  const [language, setLanguage] = useState("English");
  const [generated, setGenerated] = useState(false);
  useEffect(() => { fetch("/api/prevention/patterns", { cache: "no-store" }).then(response => response.ok ? response.json() : Promise.reject()).then((items: Pattern[]) => { const verified = items.filter(item => item.status === "VERIFIED"); setPatterns(verified); setSelectedId(verified[0]?.id || ""); }).catch(() => setPatterns([])); }, []);
  const selected = useMemo(() => patterns.find(item => item.id === selectedId), [patterns, selectedId]);
  const indicator = selected?.indicators[0];
  return <div className="page awareness-page">
    <header className="studio-header"><div><p>Awareness studio</p><h1>Turn reviewed intelligence into safer guidance.</h1><span>Draft a small, specific piece of awareness content from a verified pattern. Nothing publishes automatically.</span></div><div className="studio-boundary"><LockKeyhole/><strong>Human approval required</strong><span>Drafts are based only on verified patterns and must be checked before sharing.</span></div></header>
    <div className="studio-layout"><section className="studio-builder"><div className="studio-section-title"><span className="studio-step">1</span><div><h2>Choose verified intelligence</h2><p>Awareness content should have an evidence trail behind it.</p></div></div>{patterns.length ? <div className="verified-pattern-picker">{patterns.map(pattern => <button key={pattern.id} className={pattern.id === selectedId ? "selected" : ""} onClick={() => { setSelectedId(pattern.id); setGenerated(false); }}><div><ShieldCheck/><span><strong>{pattern.title}</strong><small>{pattern.complaint_count} supporting reports · {pattern.indicators.length} recurring indicators</small></span></div><ArrowRight/></button>)}</div> : <div className="studio-empty"><ShieldCheck/><div><strong>No verified patterns yet</strong><span>Review an emerging pattern before creating public guidance.</span><Link href="/prevention">Review intelligence <ArrowRight/></Link></div></div>}
      <div className="studio-section-title"><span className="studio-step">2</span><div><h2>Choose a simple format</h2><p>Keep the message useful, short, and easy to verify.</p></div></div><div className="format-options">{[["60-second video script",Clapperboard,"A scene-by-scene reel outline"],["Short advisory",FileText,"A concise notice for internal or public review"],["WhatsApp share card",Megaphone,"Text sized for forwarding"]].map(([name,Icon,detail]) => <button key={name as string} className={format === name ? "selected" : ""} onClick={() => { setFormat(name as string); setGenerated(false); }}><Icon/><span><strong>{name as string}</strong><small>{detail as string}</small></span></button>)}</div><div className="studio-controls"><label><Languages/>Language<select value={language} onChange={event => setLanguage(event.target.value)}><option>English</option><option>Hindi</option><option>Kannada</option><option>Marathi</option></select></label><button className="studio-generate" disabled={!selected} onClick={() => setGenerated(true)}><Sparkles/>Create draft</button></div></section>
      <aside className="studio-preview"><div className="preview-top"><div><small>Draft preview</small><strong>{generated ? "Ready for review" : "Waiting for a verified pattern"}</strong></div><span className={generated ? "preview-status ready" : "preview-status"}>{generated ? "Review" : "Locked"}</span></div>{generated && selected ? <><div className="video-preview"><div className="video-preview-grid"><span>1</span><span>2</span><span>3</span></div><Play/><small>{format}</small></div><div className="draft-copy"><p><strong>Opening</strong> A promising investment message can be designed to create urgency before you have time to check it.</p><p><strong>What to notice</strong> The reviewed pattern includes {indicator?.type_label.toLowerCase()} <b>{indicator?.display_value}</b> observed across {indicator?.case_count} reports.</p><p><strong>Safer next step</strong> Pause. Do not send money. Verify the person or organisation through a trusted channel and report suspicious messages.</p></div><div className="draft-meta"><span><Check/>Source: verified pattern</span><span><Languages/>{language}</span></div><div className="publish-lock"><LockKeyhole/><div><strong>Human review required before publishing</strong><span>Check wording, translations, legal guidance, and current contact routes.</span></div></div></> : <div className="preview-locked"><ShieldCheck/><h2>Verified intelligence becomes guidance here.</h2><p>Choose a verified pattern and create a draft to see the evidence trail, message, and approval boundary together.</p></div>}</aside></div>
    <section className="awareness-principles"><div><small>What makes this safe</small><h2>Awareness is an output of review, not a new source of truth.</h2></div><div><span><Check/> No automatic publishing</span><span><Check/> No accusations or named suspects</span><span><Check/> Pattern evidence stays linked</span><span><Check/> Review copy before distribution</span></div></section>
  </div>;
}
