"use client";

import Link from "next/link";
import { AlertTriangle, ArrowLeft, CheckCircle2, Clapperboard, Fingerprint, LoaderCircle, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

type Pattern = { id: string; title: string; status: string; behavioural_pattern?: string; review_note?: string; complaint_count: number; first_seen: string; last_seen: string; strength: string; indicators: { type_label: string; display_value: string; case_count: number; sources: string[] }[]; supporting_cases: { id: string; reference: string; summary: string; category: string; status: string; created_at: string }[]; reasons: string[]; review_history: { status: string; note?: string; reviewer: string; created_at: string }[] };
const date = (value: string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));
const label = (status: string) => status.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase());

export function PatternDetail({ id }: { id: string }) {
  const [pattern, setPattern] = useState<Pattern>(); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/prevention/patterns/${encodeURIComponent(id)}`, { cache: "no-store" }).then(response => response.ok ? response.json() : Promise.reject()).then(setPattern).catch(() => setError("This pattern could not be loaded.")); }, [id]);
  const review = async (status: string) => { setBusy(true); setError(""); const response = await fetch(`/api/prevention/patterns/${encodeURIComponent(id)}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, note }) }); if (response.ok) { setPattern(await response.json()); setNote(""); } else setError("Review status could not be saved."); setBusy(false); };
  if (!pattern && !error) return <div className="page prevention-loading"><LoaderCircle/>Loading prevention pattern…</div>;
  if (!pattern) return <div className="page prevention-error"><AlertTriangle/>{error}</div>;
  return <div className="page pattern-detail"><Link className="pattern-back" href="/prevention"><ArrowLeft/> Prevention intelligence</Link><header className="pattern-detail-hero"><div><span className={`pattern-state ${pattern.status.toLowerCase()}`}>{label(pattern.status)}</span><h1>{pattern.title}</h1><p>{pattern.complaint_count} reports appear to share recurring indicators{pattern.behavioural_pattern ? " and behavioural context" : ""}. This requires human interpretation; it is not an attribution.</p></div><div><small>SUPPORT LEVEL</small><strong>{pattern.strength}</strong><span>See the reasons below—no opaque percentage score.</span></div></header>
    <section className="pattern-detail-section"><p>WHY THIS WAS SURFACED</p><h2>Specific, source-preserving reasons</h2><div className="why-list">{pattern.reasons.map(reason => <div key={reason}><CheckCircle2/>{reason}</div>)}</div></section>
    <section className="pattern-detail-section"><p>INDICATORS</p><h2>Recurring identifiers</h2><div className="detail-indicators">{pattern.indicators.map(item => <div key={`${item.type_label}-${item.display_value}`}><small>{item.type_label}</small><strong>{item.display_value}</strong><span>Observed in {item.case_count} cases</span><em>Source: {item.sources.join(", ")}</em></div>)}</div></section>
    <section className="pattern-detail-section"><p>TIMELINE</p><h2>Observed across reports</h2><div className="pattern-timeline"><div><time>{date(pattern.first_seen)}</time><span>First supporting complaint recorded</span></div><div><time>{date(pattern.last_seen)}</time><span>Most recent supporting complaint recorded</span></div></div></section>
    <section className="pattern-detail-section"><p>RELATED CASES</p><h2>Supporting reports</h2><div className="supporting-cases">{pattern.supporting_cases.map(item => <Link key={item.id} href={`/cases/${item.id}`}><div><strong>{item.reference}</strong><span>{item.category} · {item.status}</span></div><p>{item.summary}</p></Link>)}</div></section>
    <section className="pattern-detail-section review-panel"><p>HUMAN REVIEW</p><h2>Control whether this becomes prevention intelligence</h2><span>Verification means a reviewer has assessed the supporting information. It does not establish criminal identity or liability.</span><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Reviewer note (required in a production workflow)"/><div className="review-actions"><button disabled={busy} onClick={() => void review("VERIFIED")}><ShieldCheck/>Verify pattern</button><button disabled={busy} onClick={() => void review("NEEDS_MORE_EVIDENCE")}>Needs more evidence</button><button disabled={busy} onClick={() => void review("DISMISSED")}>Dismiss</button></div>{error && <div className="prevention-error"><AlertTriangle/>{error}</div>}{pattern.review_history.map((item, index) => <div className="review-history" key={`${item.created_at}-${index}`}><strong>{label(item.status)}</strong><span>{item.note || "No reviewer note recorded."}</span><small>{item.reviewer} · {date(item.created_at)}</small></div>)}</section>
    {pattern.status === "VERIFIED" && <section className="pattern-detail-section prevention-actions"><p>PREVENTION ACTIONS</p><h2>Turn this pattern into prevention</h2><span>Use the reviewed tactics and signal types to prepare public guidance without publishing case identifiers.</span><div><Link className="awareness-video-action" href={{ pathname: "/awareness", query: { pattern: pattern.id } }}><Clapperboard/>Create awareness video</Link><button onClick={() => window.alert("Internal watchlist preparation is an officer-controlled workflow.")}><Fingerprint/>Add to internal watchlist</button></div><small><ShieldCheck/> Video drafts and future incident warnings remain under human control.</small></section>}
  </div>;
}
